Hero villain

+ = - * / % // /=

= += -= *= /= %=

+ - * / // % ^

== != > < >= <=

1234 999999 

3.14 2.718281828459045

( ) [ ] : , .

'a' "THis is a string baby
"

# This is a commment

## This is a multiline comment

yes multiline
##

and or not is

character scene template dialogue narrate choice option ask if elif else repeat for show start end becomes until times

true false return in error fixed break continue pass with

the a an as then of to



"Hello, world!" "infinity" "String with spaces" ""

'i' 'a' 'Z'


143variable 'Aa' 9name my$var 123.456.789 "unterminated string
