# identifiers
Hero villain

# assignment operators
= += -= *= /= %=

# arithmetic operators
+ - * / // % ^

# relational operators
== != > < >= <=

# logical operators (keywords)
and or not is

# keywords
is character scene template dialogue narrate choice option ask if elif else repeat for show start end becomes until times

# reserved words 
true false return in error fixed break continue pass with

# noise word
the a an as then of to

# Integer Literal
1234 999999

# Float Literal
3.14 2.718281828459045

# String Literal
"Hello, world!" "infinity" "String with spaces" ""

# character literals #
'i' 'a' 'Z'

# comments
# this is a single line comment
## this is multi-line 
comment ##

# delimiters
( ) [ ] : , .

# invalids
_var 143variable 'Aa' '' my$var 123.456.789 "unterminated string

